# Look! A turtle!
import turtle as trtl
pen = trtl.Turtle()
pen = trtl.Turtle()
pen.pensize(5)
pen.speed(0)

# The hair 
pen.setheading(0)
pen.color("orange")
pen.up()
pen.goto(-20,50)
pen.down()
pen.begin_fill()
pen.circle(50)
pen.end_fill()
pen.up()
pen.goto(-35,40)
pen.down()
pen.begin_fill()
pen.circle(45)
pen.end_fill()
pen.up()
pen.goto(-50,30)
pen.down()
pen.begin_fill()
pen.circle(30)
pen.end_fill()
pen.up()
pen.goto(20,50)
pen.down()
pen.begin_fill()
pen.circle(50)
pen.end_fill()
pen.up()
pen.goto(35,40)
pen.down()
pen.begin_fill()
pen.circle(45)
pen.end_fill()
pen.up()
pen.goto(40,30)
pen.down()
pen.begin_fill()
pen.circle(30)
pen.end_fill()

#Moving turtle to the head
pen.up()
pen.goto(0,50)
pen.down()

# Making head and new color
pen.color("sandybrown")
pen.begin_fill()
pen.circle(50)
pen.end_fill()

#Do neck

pen.begin_fill()
pen.up()
pen.goto(15,50)
pen.down()
pen.right(90)
pen.forward(30)
pen.right(90)
pen.forward(30)
pen.right(90)
pen.forward(30)
pen.right(90)
pen.forward(30)
pen.end_fill()

#shoulders
pen.setheading(90)
pen.begin_fill()
pen.up()
pen.goto(0,10)
pen.down()
pen.circle(15)
pen.up()
pen.goto(30,5)
pen.down()
pen.circle(15)
pen.end_fill()

# arms
pen.begin_fill()
pen.right(180)
pen.forward(50)
pen.right(45)
pen.forward(30)
pen.right(135)
pen.forward(55)
pen.end_fill()
pen.up()
pen.goto(-35,10)
pen.down()
pen.begin_fill()
pen.right(180)
pen.forward(50)
pen.left(45)
pen.forward(30)
pen.left(135)
pen.forward(55)
pen.end_fill()

#Dress and new color
pen.color("grey")
pen.up()
pen.goto(-10,-5)
pen.down()
pen.begin_fill()
pen.circle(10)
pen.end_fill()
pen.right(180)
pen.forward(100)
pen.left(90)

#Bottom of dress
bottom=0
while (bottom<5):
    pen.begin_fill()
    pen.circle(-10)
    pen.up()
    pen.forward(20)
    pen.down()
    pen.end_fill()
    bottom+=1
 
#moredress
pen.up()
pen.back(20)
pen.down()
pen.left(128)
pen.forward(70)
pen.up()
pen.forward(30)
pen.down()
pen.forward(30)


# eyes 
eyecolor = 0
while (eyecolor < 5):
    pen.setheading(0)
    pen.color("red")
    pen.begin_fill()
    pen.up()
    pen.goto(-8,105)
    pen.down()
    pen.circle(10)
    pen.end_fill()
    pen.up()
    pen.goto(18,105)
    pen.down()
    pen.begin_fill()
    pen.circle(10)
    pen.end_fill()
    pen.setheading(0)
    pen.color("blue")
    pen.begin_fill()
    pen.up()
    pen.goto(-8,105)
    pen.down()
    pen.circle(10)
    pen.end_fill()
    pen.up()
    pen.goto(18,105)
    pen.down()
    pen.begin_fill()
    pen.circle(10)
    pen.end_fill()
eyecolor +=1

# Look! The end of the turtle!
pen.hideturtle() 
wn = trtl.Screen()
wn.mainloop()